
export const RECEIVE_USERS = 'RECEIVE_USERS';
export type RECEIVE_USERS_TYPE = typeof RECEIVE_USERS;

export const ADD_USER_QUESTIONS = 'ADD_USER_QUESTION';
export type ADD_USER_QUESTIONS_TYPE = typeof ADD_USER_QUESTIONS;

export type actionType = RECEIVE_USERS_TYPE | ADD_USER_QUESTIONS_TYPE